-- V1: the full schema, as the entity classes describe it today.
--
-- This is the Flyway baseline for Supabase (Postgres). It replaces
-- spring.jpa.hibernate.ddl-auto=update on that profile: from here on, schema
-- changes are new V<n>__*.sql files in this directory, never Hibernate edits.
--
-- Everything is IF NOT EXISTS on purpose: a Supabase database that Hibernate
-- already built (from an earlier run with ddl-auto=update) adopts this
-- baseline without being touched, and a fresh database gets the whole schema.
--
-- Deliberate shapes carried over from the entities:
--   * Enum-ish columns (severity, status, kind, ...) are plain VARCHAR, never
--     a native ENUM or a CHECK list - adding a constant must never need DDL.
--   * Bugs reference projects and people by NAME, not foreign key, so renames
--     and retirements never rewrite history. The only real FK is the one
--     Hibernate itself owns: bug_assignees -> bugs.
--   * blocked_by is a bare id: a deleted blocker should read as "not blocked",
--     not cascade this bug away.

-- --- the people and the projects --------------------------------------------

create table if not exists team_members (
    id         bigint generated by default as identity primary key,
    name       varchar(80)  not null,
    email      varchar(120) not null,
    active     boolean      not null,
    created_at timestamp(6) not null,
    constraint uk_team_members_email unique (email)
);

create table if not exists projects (
    id         bigint generated by default as identity primary key,
    name       varchar(80)  not null,
    active     boolean      not null,
    created_at timestamp(6) not null,
    constraint uk_projects_name unique (name)
);

-- One column of one project's board. status_key is what a bug stores and is
-- immutable; label is free to rename. Project held as its name, same as bugs.
create table if not exists board_columns (
    id         bigint generated by default as identity primary key,
    project    varchar(80) not null,
    status_key varchar(40) not null,
    label      varchar(40) not null,
    colour     varchar(20) not null,
    done_state boolean     not null,
    notify     varchar(20) not null,
    position   integer     not null,
    constraint uk_column_project_key unique (project, status_key)
);

-- --- the bugs themselves -----------------------------------------------------

create table if not exists bugs (
    id                 bigint generated by default as identity primary key,
    title              varchar(150)  not null,
    description        varchar(4000),
    steps_to_reproduce varchar(4000),
    expected_result    varchar(1000),
    actual_result      varchar(1000),
    severity           varchar(20)   not null,
    status             varchar(40)   not null,
    environment        varchar(20),
    project            varchar(80),
    module             varchar(80),
    reported_by        varchar(80),
    blocked_by         bigint,
    deleted_at         timestamp(6),
    deleted_by         varchar(80),
    created_at         timestamp(6)  not null,
    updated_at         timestamp(6)  not null
);

-- @ElementCollection with @OrderColumn: position keeps "the first assignee" a
-- stable idea. The one true foreign key - Hibernate owns this table outright.
create table if not exists bug_assignees (
    bug_id   bigint  not null,
    position integer not null,
    assignee varchar(80),
    primary key (bug_id, position),
    constraint fk_bug_assignees_bug foreign key (bug_id) references bugs (id)
);

create table if not exists bug_comments (
    id         bigint generated by default as identity primary key,
    bug_id     bigint        not null,
    text       varchar(2000) not null,
    created_by varchar(80),
    created_at timestamp(6)  not null
);

-- Metadata only - the bytes live on disk or in a bucket.
create table if not exists bug_attachments (
    id           bigint generated by default as identity primary key,
    bug_id       bigint       not null,
    file_name    varchar(255) not null,
    stored_name  varchar(120) not null,
    content_type varchar(120),
    size_bytes   bigint       not null,
    uploaded_by  varchar(80),
    uploaded_at  timestamp(6) not null
);

create table if not exists bug_history (
    id         bigint generated by default as identity primary key,
    bug_id     bigint       not null,
    action     varchar(40)  not null,
    old_value  varchar(255),
    new_value  varchar(255),
    actor      varchar(80),
    changed_at timestamp(6) not null
);

-- A page of notes or a sheet of test cases, written against one bug.
create table if not exists bug_docs (
    id         bigint generated by default as identity primary key,
    bug_id     bigint          not null,
    title      varchar(150)    not null,
    type       varchar(20)     not null,
    content    varchar(100000),
    summary    varchar(80),
    created_by varchar(80),
    created_at timestamp(6)    not null,
    updated_by varchar(80),
    updated_at timestamp(6)    not null
);

-- --- around the bugs ---------------------------------------------------------

-- Exactly one of bug_id / link is set - hence both nullable.
create table if not exists notifications (
    id         bigint generated by default as identity primary key,
    bug_id     bigint,
    type       varchar(30)  not null,
    recipient  varchar(80),
    message    varchar(255) not null,
    link       varchar(300),
    is_read    boolean      not null,
    created_at timestamp(6) not null
);

-- A project's documents area: folder, page, sheet, file or link in one table,
-- discriminated by kind. parent_id is the tree, null at the root.
create table if not exists project_resources (
    id           bigint generated by default as identity primary key,
    project_id   bigint          not null,
    parent_id    bigint,
    kind         varchar(20)     not null,
    name         varchar(200)    not null,
    note         varchar(400),
    url          varchar(2000),
    stored_name  varchar(120),
    content_type varchar(120),
    size_bytes   bigint          not null,
    content      varchar(200000),
    summary      varchar(80),
    created_by   varchar(80),
    created_at   timestamp(6)    not null,
    updated_by   varchar(80),
    updated_at   timestamp(6)    not null
);

-- --- indexes -----------------------------------------------------------------

-- The one the entity declares (drawing one folder is the hot path there).
create index if not exists ix_resources_folder on project_resources (project_id, parent_id);

-- The lookups every bug page makes. Hibernate never created these on H2 - a
-- local file database never noticed - but a shared Postgres will. No index
-- for bug_assignees: its primary key already leads with bug_id.
create index if not exists ix_bug_comments_bug    on bug_comments (bug_id);
create index if not exists ix_bug_attachments_bug on bug_attachments (bug_id);
create index if not exists ix_bug_history_bug     on bug_history (bug_id);
create index if not exists ix_bug_docs_bug        on bug_docs (bug_id);
create index if not exists ix_bugs_project        on bugs (project);
create index if not exists ix_notifications_recipient on notifications (recipient);

-- --- row level security ------------------------------------------------------

-- Supabase's Data API (PostgREST) exposes every table in the public schema to
-- anyone holding the project's anon key. This app never uses that API - all
-- access goes through JDBC as the postgres role, which owns these tables and
-- so is not subject to RLS. Enabling RLS with no policies therefore changes
-- nothing for the app and closes the Data API to everyone else.

alter table team_members      enable row level security;
alter table projects          enable row level security;
alter table board_columns     enable row level security;
alter table bugs              enable row level security;
alter table bug_assignees     enable row level security;
alter table bug_comments      enable row level security;
alter table bug_attachments   enable row level security;
alter table bug_history       enable row level security;
alter table bug_docs          enable row level security;
alter table notifications     enable row level security;
alter table project_resources enable row level security;
