-- V8: named filter sets, shared with everyone, deletable by whoever made them.

create table if not exists saved_filters (
    id         bigint generated by default as identity primary key,
    name       varchar(60)   not null,
    project    varchar(80),
    query      varchar(1000) not null,
    created_by varchar(80)   not null,
    created_at timestamp(6)  not null
);

create index if not exists idx_saved_filters_project on saved_filters (project);

alter table saved_filters enable row level security;
